#!/bin/bash

REPO="https://raw.githubusercontent.com/COLD1224/AgateRepository/main/downloads"

case "$1" in
    help)
        echo "Agate Package Manager"

        echo "commands:"
        echo "inst (installs package)"
        echo "rm (removes package)"
        echo "help (shows commands again"
echo "made AGLT (Azure Gemstone Linux Tools)"
        ;;
    inst)
        # install package
        ;;
    rm)
        # remove package
        ;;
    *)
        echo "Unknown command. check 'agate help' maybe you misspelled it."
        ;;
esac

